CREATE SCHEMA IF NOT EXISTS finance_data;

SET search_path TO finance_data;

CREATE TABLE STOCKS (
	TICKER VARCHAR(10) PRIMARY KEY,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	SECTOR VARCHAR(50) NOT NULL,
	INDUSTRY VARCHAR(50) NOT NULL
);

CREATE TABLE PRICES (
	ID SERIAL PRIMARY KEY,
	TICKER VARCHAR(10) REFERENCES STOCKS (TICKER),
	DATE DATE NOT NULL,
	OPEN NUMERIC(11, 3) NOT NULL,
	CLOSE NUMERIC(11, 3) NOT NULL,
	HIGH NUMERIC(11, 3) NOT NULL,
	LOW NUMERIC(11, 3) NOT NULL, 
	CONSTRAINT UNIQUE_PRICES UNIQUE(TICKER, DATE)
);

CREATE TABLE FUNDAMENTALS (
	ID SERIAL PRIMARY KEY,
	TICKER VARCHAR(10) REFERENCES STOCKS (TICKER),
	REPORT_DATE DATE NOT NULL,
	PE_RATIO NUMERIC(10, 4) NOT NULL,
	MARKET_CAP BIGINT NOT NULL,
	DEBT_TO_EQUITY NUMERIC(10, 4) NOT NULL,
	EARNINGS_PER_SHARE NUMERIC(10, 4) NOT NULL, 
	CONSTRAINT UNIQUE_FUNDAMENTALS UNIQUE(TICKER, REPORT_DATE)
);

CREATE TABLE ECONOMIC_INDICATORS (
	ID SERIAL PRIMARY KEY,
	DATE DATE NOT NULL,
	GDP_GROWTH NUMERIC(6, 3) NOT NULL,
	INFLATION_RATE NUMERIC(6, 3) NOT NULL,
	UNEMPLOYMENT_RATE NUMERIC(6, 3) NOT NULL,
	CPI NUMERIC(10, 3) NOT NULL,
	CONSTRAINT UNIQUE_MACRO UNIQUE(DATE)
);